export type Lang = 'en' | 'fr'

export const COPY = {
  nav: {
    en: ['Programs', 'Tuition', 'Locations', 'FAQ', 'Contact'],
    fr: ['Programmes', 'Frais', 'Emplacements', 'FAQ', 'Contact'],
  },
  hero: {
    en: {
      eyebrow: 'Welcome to Ile CoCo · Montréal',
      title1: 'Where',
      title2: 'little hearts',
      title3: 'bloom in',
      title4: 'good hands',
      lead: 'A Montessori-inspired daycare nestled on Somerled, where curiosity is honoured, mealtimes are sacred, and every child is met with the gentleness they deserve.',
      cta1: 'Join the waiting list',
      cta2: 'Book a visit',
      since: 'since 2018',
      stat1: '343',
      stat1Label: 'Families guided',
      stat2: '165',
      stat2Label: 'Little graduates',
      stat3: '8 yrs',
      stat3Label: 'Of patient care',
    },
    fr: {
      eyebrow: 'Bienvenue à Ile CoCo · Montréal',
      title1: 'Là où',
      title2: 'les petits cœurs',
      title3: 'fleurissent en',
      title4: 'bonnes mains',
      lead: "Une garderie d'inspiration Montessori nichée sur Somerled, où la curiosité est honorée, les repas sont sacrés, et chaque enfant est accueilli avec la douceur qu'il mérite.",
      cta1: "Liste d'attente",
      cta2: 'Réserver une visite',
      since: 'depuis 2018',
      stat1: '343',
      stat1Label: 'Familles accompagnées',
      stat2: '165',
      stat2Label: 'Petits diplômés',
      stat3: '8 ans',
      stat3Label: 'De soins patients',
    },
  },
  mission: {
    en: {
      eyebrow: 'Our Promise',
      title1: 'A second home,',
      title2: 'thoughtfully kept',
      body: 'We believe early childhood is sacred. So we built Ile CoCo as a slow, sun-drenched home — a place where children are not rushed through their days, but invited to wonder, to taste, to listen, to learn at the pace their hearts can hold.',
      bullets: [
        'Mixed-age Montessori environments',
        'House-made, allergen-aware meals',
        'Bilingual rhythm — English & French',
        'A small-group ratio, always',
      ],
      cta: 'Plan a visit',
      pill: 'Made with care',
    },
    fr: {
      eyebrow: 'Notre Promesse',
      title1: 'Un deuxième foyer,',
      title2: 'soigneusement tenu',
      body: "Nous croyons que la petite enfance est sacrée. Nous avons donc créé Ile CoCo comme une maison lente et baignée de soleil — un lieu où les enfants ne sont pas pressés, mais invités à s'émerveiller, à goûter, à écouter, à apprendre au rythme de leur cœur.",
      bullets: [
        'Environnements Montessori multi-âges',
        'Repas maison, attentifs aux allergies',
        'Rythme bilingue — Anglais & Français',
        'Petits groupes, toujours',
      ],
      cta: 'Planifier une visite',
      pill: 'Fait avec soin',
    },
  },
  services: {
    en: {
      eyebrow: 'How we nurture',
      title1: 'Six gentle',
      title2: 'rhythms of the day',
      sub: 'Each day at Ile CoCo follows the same warm cadence — small rituals that, repeated with love, become the texture of childhood.',
      items: [
        { tag: '01', name: 'Nourishment', desc: 'Three slow, fresh meals prepared in our own kitchen — built around what little bodies actually need.' },
        { tag: '02', name: 'Free Play', desc: 'Unhurried, child-led play — the kind where imagination has time to wander into corners and stay a while.' },
        { tag: '03', name: 'Quiet Learning', desc: 'Montessori materials, gentle prompts, and the dignity of being trusted to figure something out.' },
        { tag: '04', name: 'Music & Song', desc: 'A daily circle of songs in two languages, instruments small enough for any hand, voices welcomed exactly as they are.' },
        { tag: '05', name: 'Two Languages', desc: 'English and French woven through the day — never drilled, always lived. Bilingual the way Montréal is.' },
        { tag: '06', name: 'Daily Journal', desc: 'A short, honest note home each evening — what they ate, what they made, what made them laugh today.' },
      ],
    },
    fr: {
      eyebrow: 'Comment nous prenons soin',
      title1: 'Six doux',
      title2: 'rythmes de la journée',
      sub: "Chaque journée à Ile CoCo suit la même cadence chaleureuse — de petits rituels qui, répétés avec amour, deviennent la texture de l'enfance.",
      items: [
        { tag: '01', name: 'Nourriture', desc: 'Trois repas lents et frais préparés dans notre cuisine — pensés pour ce dont les petits corps ont vraiment besoin.' },
        { tag: '02', name: 'Jeu libre', desc: "Un jeu sans hâte, mené par l'enfant — celui où l'imagination a le temps de s'égarer dans les coins." },
        { tag: '03', name: 'Apprentissage', desc: 'Du matériel Montessori, des invitations douces, et la dignité de chercher par soi-même.' },
        { tag: '04', name: 'Musique', desc: 'Un cercle quotidien de chansons en deux langues, des instruments adaptés aux petites mains.' },
        { tag: '05', name: 'Bilingue', desc: "L'anglais et le français tissés dans la journée — jamais imposés, toujours vécus. Bilingue comme Montréal." },
        { tag: '06', name: 'Journal', desc: "Un petit mot honnête chaque soir — ce qu'ils ont mangé, fabriqué, ce qui les a fait rire aujourd'hui." },
      ],
    },
  },
  why: {
    en: {
      eyebrow: 'Why parents choose us',
      title1: 'Care that is',
      title2: 'kind, safe, & trusted',
      sub: 'We are licensed, small, and deeply attentive. Here is what that looks like, day to day.',
      items: [
        { title: 'Licensed & inspected', desc: 'Provincially-permitted, insured, and routinely inspected.' },
        { title: 'Small-group ratios', desc: 'Never more than seven children per educator. Often fewer.' },
        { title: 'House-made meals', desc: 'Cooked on-site, never reheated. Allergen-aware menus weekly.' },
        { title: 'Calm, prepared rooms', desc: 'Natural light, child-height shelves, no screens — ever.' },
        { title: 'Trained Montessori staff', desc: 'Educators with formal AMI/AMS training and CPR certification.' },
        { title: 'A real journal home', desc: 'A handwritten note each day. Photos weekly. No anxious apps.' },
      ],
    },
    fr: {
      eyebrow: 'Pourquoi les parents nous choisissent',
      title1: 'Des soins',
      title2: 'doux, sûrs & fiables',
      sub: 'Nous sommes accrédités, petits, et profondément attentifs. Voici à quoi ça ressemble, au quotidien.',
      items: [
        { title: 'Permis & inspecté', desc: 'Permis provincial, assuré et inspecté régulièrement.' },
        { title: 'Petits groupes', desc: 'Jamais plus de sept enfants par éducateur. Souvent moins.' },
        { title: 'Repas maison', desc: 'Cuisinés sur place, jamais réchauffés. Menus hebdomadaires.' },
        { title: 'Espaces préparés', desc: "Lumière naturelle, étagères à hauteur d'enfant, pas d'écrans." },
        { title: 'Équipe Montessori', desc: 'Éducateurs formés AMI/AMS et certifiés en RCR.' },
        { title: 'Un vrai journal', desc: 'Un mot manuscrit chaque jour. Des photos chaque semaine.' },
      ],
    },
  },
  journey: {
    en: {
      eyebrow: 'Watch our journey',
      title1: 'Small moments,',
      title2: 'captured tenderly',
      sub: 'A short film of a slow place — gardens in May, dough on small fingers, the first time someone pours their own water.',
      watch: 'Watch the film',
      pressPlay: 'press play ↓',
      sideLabels: ['Splash days', 'Snow days', 'Apple days'],
    },
    fr: {
      eyebrow: 'Notre quotidien',
      title1: 'De petits moments,',
      title2: 'saisis avec tendresse',
      sub: "Un court film d'un lieu lent — les jardins en mai, la pâte sur de petits doigts, la première fois qu'on verse son propre verre d'eau.",
      watch: 'Voir le film',
      pressPlay: 'appuyez ↓',
      sideLabels: ["Jours d'eau", 'Jours de neige', 'Jours de pommes'],
    },
  },
  gallery: {
    en: {
      eyebrow: 'Inside Ile CoCo',
      title1: 'A peek into',
      title2: 'our two homes',
      sub: 'Sun-filled rooms on Somerled, the warm hallway with our little monkeys, snowy afternoons, splashy summers, and dinners that look like art.',
      cta: 'See more on Instagram',
      captions: [
        'The little monkey wall',
        'Sunflower room',
        'Indoor playground',
        'Treehouse corner',
        'Plates we adore',
        'Holiday morning',
        'Costumed staff',
        'Splash days',
      ],
    },
    fr: {
      eyebrow: "À l'intérieur",
      title1: 'Un aperçu de',
      title2: 'nos deux foyers',
      sub: "Des pièces baignées de soleil sur Somerled, le corridor chaleureux avec nos petits singes, les après-midis enneigés, les étés éclaboussants.",
      cta: 'Plus sur Instagram',
      captions: [
        'Le mur des singes',
        'Salle des tournesols',
        'Aire de jeux',
        'Coin cabane',
        'Assiettes adorées',
        'Matin de fête',
        'Équipe costumée',
        "Jours d'eau",
      ],
    },
  },
  testimonials: {
    en: {
      eyebrow: 'Words from our families',
      title1: 'What parents',
      title2: 'quietly tell us',
      items: [
        { quote: 'We toured eight daycares. Ile CoCo was the only one that felt like a home and not a facility. Two years in, it still does.', name: 'Camille & Theo R.', role: 'Parents of Léa, age 3' },
        { quote: 'The educators know my daughter. Not just her name — her moods, what makes her laugh, what scares her at nap time. That is rare.', name: 'Sofia M.', role: 'Parent of Aïcha, age 2' },
        { quote: 'Our son started with three words. By spring, he was singing in two languages and arguing in both. We could not have asked for more.', name: 'David & Yann L.', role: 'Parents of Noah, age 4' },
      ],
    },
    fr: {
      eyebrow: 'Mots de nos familles',
      title1: 'Ce que les parents',
      title2: 'nous disent tout bas',
      items: [
        { quote: "On a visité huit garderies. Ile CoCo était la seule qui se sentait comme une maison et non un établissement. Deux ans plus tard, c'est toujours vrai.", name: 'Camille & Théo R.', role: 'Parents de Léa, 3 ans' },
        { quote: "Les éducatrices connaissent ma fille. Pas juste son prénom — ses humeurs, ce qui la fait rire, ce qui l'effraie à la sieste. C'est rare.", name: 'Sofia M.', role: "Maman d'Aïcha, 2 ans" },
        { quote: 'Notre fils est arrivé avec trois mots. Au printemps, il chantait en deux langues et argumentait dans les deux. On ne pouvait rêver mieux.', name: 'David & Yann L.', role: 'Parents de Noah, 4 ans' },
      ],
    },
  },
  tuition: {
    en: {
      eyebrow: 'Tuition',
      title1: 'Honest pricing,',
      title2: 'no surprises',
      sub: 'Subsidized and full-fee spots, both with the same care. We will walk you through it on a tour — these are starting points.',
      items: [
        { tag: 'Subsidized', price: '$9.35', per: '/ day', note: "For eligible families through Quebec's reduced-contribution program." },
        { tag: 'Full-fee', price: '$58', per: '/ day', note: 'Includes meals, snacks, materials, outings — everything but the rain boots.' },
        { tag: 'Drop-in', price: '$72', per: '/ day', note: 'By availability, for siblings or short-term needs.' },
      ],
      includes: 'All tuition includes house-made meals, snacks, all materials, and seasonal outings.',
      mostCommon: 'Most common',
      cta: 'Request the full guide',
    },
    fr: {
      eyebrow: 'Frais',
      title1: 'Tarifs honnêtes,',
      title2: 'sans surprises',
      sub: 'Places subventionnées et au tarif régulier, avec le même soin. Nous vous expliquerons tout lors de la visite.',
      items: [
        { tag: 'Subventionné', price: '9,35 $', per: '/ jour', note: 'Pour les familles admissibles au programme à contribution réduite du Québec.' },
        { tag: 'Tarif régulier', price: '58 $', per: '/ jour', note: 'Comprend repas, collations, matériel, sorties — tout sauf les bottes de pluie.' },
        { tag: 'Sur appel', price: '72 $', per: '/ jour', note: 'Selon disponibilité, pour fratries ou besoins ponctuels.' },
      ],
      includes: 'Tous les frais incluent les repas maison, les collations, le matériel et les sorties saisonnières.',
      mostCommon: 'Le plus courant',
      cta: 'Demander le guide complet',
    },
  },
  locations: {
    en: {
      eyebrow: 'Two homes, one heart',
      title1: 'Find us in',
      title2: 'your neighbourhood',
      sub: 'Both locations are licensed, both are small, and both feel like a home before they feel like a daycare.',
      labels: { addr: 'Address', hours: 'Hours', ages: 'Ages', phone: 'Phone' },
      items: [
        { name: 'Somerled', subtitle: 'Our original home · since 2018', addr: '6624 av. Somerled', city: 'Montréal, QC H4V 1S5', hours: 'Mon — Fri · 7:30 — 18:00', ages: '18 months — 5 years', phone: '(514) 574-4695', mapHint: 'NDG · near Décarie' },
        { name: 'Côte-des-Neiges', subtitle: 'Our newer home · opened 2023', addr: '6620 Côte-des-Neiges', city: 'Montréal, QC H3S 2A5', hours: 'Mon — Fri · 7:30 — 18:00', ages: '18 months — 5 years', phone: '(514) 574-4696', mapHint: 'CDN · near Université de Montréal' },
      ],
      visit: 'Plan a visit',
    },
    fr: {
      eyebrow: 'Deux foyers, un seul cœur',
      title1: 'Retrouvez-nous',
      title2: 'dans votre quartier',
      sub: 'Les deux emplacements sont accrédités, petits, et ressemblent à un foyer avant de ressembler à une garderie.',
      labels: { addr: 'Adresse', hours: 'Heures', ages: 'Âges', phone: 'Téléphone' },
      items: [
        { name: 'Somerled', subtitle: "Notre foyer d'origine · depuis 2018", addr: '6624 av. Somerled', city: 'Montréal, QC H4V 1S5', hours: 'Lun — Ven · 7h30 — 18h00', ages: '18 mois — 5 ans', phone: '(514) 574-4695', mapHint: 'NDG · près de Décarie' },
        { name: 'Côte-des-Neiges', subtitle: 'Notre nouveau foyer · ouvert 2023', addr: '6620 Côte-des-Neiges', city: 'Montréal, QC H3S 2A5', hours: 'Lun — Ven · 7h30 — 18h00', ages: '18 mois — 5 ans', phone: '(514) 574-4696', mapHint: 'CDN · près de UdeM' },
      ],
      visit: 'Planifier une visite',
    },
  },
  faq: {
    en: {
      eyebrow: 'Honest answers',
      title1: 'Questions parents',
      title2: 'actually ask',
      tapHint: 'tap to open',
      items: [
        { q: 'What ages do you welcome?', a: 'We welcome children from 18 months through 5 years. Our rooms are mixed-age, the way Montessori is meant to be.' },
        { q: 'How do you handle food allergies?', a: 'Every menu is reviewed weekly for the allergens we host that month. Our chef and lead educator both hold current food-safety credentials.' },
        { q: 'What is your educator-to-child ratio?', a: 'Maximum of seven children per educator. We often run smaller — that is a deliberate choice, not a coincidence.' },
        { q: 'Do you have a waiting list?', a: 'Yes — and we are honest about it. Spots open three to four times a year. Once you join the list, we keep you informed by email, not by silence.' },
        { q: 'What about screens?', a: "There are no screens in our rooms. Children's days are full of real things: water, paint, dough, dirt, songs, books, each other." },
      ],
    },
    fr: {
      eyebrow: 'Des réponses honnêtes',
      title1: 'Questions que',
      title2: 'les parents posent',
      tapHint: 'cliquez pour ouvrir',
      items: [
        { q: 'Quels âges accueillez-vous?', a: "De 18 mois à 5 ans. Nos groupes sont multi-âges, comme Montessori l'a pensé." },
        { q: 'Comment gérez-vous les allergies?', a: 'Chaque menu est révisé chaque semaine pour les allergènes du mois. Notre chef et notre éducatrice principale détiennent les certifications en salubrité alimentaire.' },
        { q: 'Quel est le ratio éducateur-enfant?', a: "Maximum sept enfants par éducateur. Souvent moins — c'est un choix délibéré." },
        { q: 'Avez-vous une liste d\'attente?', a: "Oui — et nous sommes honnêtes à ce sujet. Des places s'ouvrent trois à quatre fois par an. Nous vous tenons informés par courriel, pas par silence." },
        { q: 'Et les écrans?', a: 'Aucun écran dans nos espaces. Les journées sont pleines de choses vraies : eau, peinture, pâte, terre, chansons, livres, les autres.' },
      ],
    },
  },
  newsletter: {
    en: {
      eyebrow: 'Stay close',
      title1: 'A letter,',
      title2: 'once a season',
      sub: 'Four times a year, a slow note from the home: a recipe the children loved, a photo from the garden, what we are reading aloud at story time.',
      placeholder: 'your@email.com',
      cta: 'Subscribe',
      promise: 'No spam. Four notes a year. Unsubscribe with one click.',
      success: 'Thank you. The next letter is coming.',
    },
    fr: {
      eyebrow: 'Rester proche',
      title1: 'Une lettre,',
      title2: 'à chaque saison',
      sub: "Quatre fois par année, un mot lent du foyer : une recette adorée, une photo du jardin, ce que nous lisons à l'heure du conte.",
      placeholder: 'votre@courriel.com',
      cta: "S'abonner",
      promise: 'Pas de spam. Quatre lettres par année. Désinscription en un clic.',
      success: 'Merci. La prochaine lettre arrive bientôt.',
    },
  },
  social: {
    en: {
      eyebrow: '@ilecoco',
      title1: 'Follow along',
      title2: 'on Instagram',
      sub: 'Quiet daily moments — not curated, just true.',
    },
    fr: {
      eyebrow: '@ilecoco',
      title1: 'Suivez-nous',
      title2: 'sur Instagram',
      sub: 'De petits moments quotidiens — non filtrés, juste vrais.',
    },
  },
  cta: {
    en: {
      title1: 'Ready to find your',
      title2: 'child a home?',
      sub: 'Tours are slow, by appointment, and always include tea.',
      cta1: 'Book a visit',
      cta2: 'Join waiting list',
      formLabel: 'Your email',
      formPlaceholder: 'your@email.com',
      formCta: 'Tell me more',
      formSuccess: "Thank you. We'll be in touch within a day or two.",
    },
    fr: {
      title1: 'Prêts à trouver',
      title2: 'un foyer pour votre enfant?',
      sub: "Les visites sont lentes, sur rendez-vous, et toujours accompagnées d'un thé.",
      cta1: 'Réserver une visite',
      cta2: "Liste d'attente",
      formLabel: 'Votre courriel',
      formPlaceholder: 'votre@courriel.com',
      formCta: 'En savoir plus',
      formSuccess: 'Merci. Nous vous contactons sous un jour ou deux.',
    },
  },
  wizard: {
    en: {
      title: 'Join the waiting list',
      subtitle: 'Three short steps. We will read every word.',
      stepLabels: ['About your child', 'Your preferences', 'How we reach you'],
      step: (n: number, total: number) => `Step ${n} of ${total}`,
      back: 'Back',
      next: 'Continue',
      submit: 'Send to Ile CoCo',
      sending: 'Sending…',
      cancel: 'Close',
      success: {
        title: 'We have your note.',
        body: 'Thank you. A real human will reply within a day or two — by email, with your name.',
        secondary: 'Close',
      },
      error: {
        title: 'Something went sideways.',
        retry: 'Try again',
      },
      child: {
        firstName: "Child's first name",
        firstNamePh: 'Léa',
        dob: 'Date of birth',
        ageHint: (y: number, m: number) =>
          y === 0 ? (m === 1 ? '1 month old' : `${m} months old`) : y === 1 ? `1 year, ${m} mo` : `${y} years, ${m} mo`,
      },
      preferences: {
        location: 'Preferred location',
        locations: {
          somerled: 'Somerled',
          'cote-des-neiges': 'Côte-des-Neiges',
          either: 'Either is fine',
        },
        startDate: 'Hoped-for start date',
        startDateHint: 'A best guess is fine — we will work it out together.',
        careType: 'Type of care',
        careTypes: { 'full-time': 'Full-time', 'part-time': 'Part-time' },
      },
      contact: {
        parentName: 'Your name',
        parentNamePh: 'Camille Dupont',
        email: 'Email',
        emailPh: 'you@example.com',
        phone: 'Phone',
        phonePh: '(514) 000-0000',
        heardFrom: 'How did you hear about us? (optional)',
        heardFromPh: 'A friend, Instagram, walking by…',
        notes: 'Anything we should know? (optional)',
        notesPh: 'Allergies, a sibling already with us, special days…',
      },
      validation: {
        required: 'Please fill this in',
        emailInvalid: 'That email looks off',
        phoneShort: 'Phone looks too short',
        dateInPast: 'Date must be in the past',
      },
    },
    fr: {
      title: "Liste d'attente",
      subtitle: 'Trois petites étapes. Nous lirons chaque mot.',
      stepLabels: ['Votre enfant', 'Vos préférences', 'Comment vous joindre'],
      step: (n: number, total: number) => `Étape ${n} sur ${total}`,
      back: 'Retour',
      next: 'Continuer',
      submit: 'Envoyer à Ile CoCo',
      sending: 'Envoi…',
      cancel: 'Fermer',
      success: {
        title: 'Nous avons reçu votre mot.',
        body: 'Merci. Une vraie personne vous répondra sous un jour ou deux — par courriel, avec votre prénom.',
        secondary: 'Fermer',
      },
      error: {
        title: "Quelque chose n'a pas fonctionné.",
        retry: 'Réessayer',
      },
      child: {
        firstName: "Prénom de l'enfant",
        firstNamePh: 'Léa',
        dob: 'Date de naissance',
        ageHint: (y: number, m: number) =>
          y === 0 ? (m === 1 ? '1 mois' : `${m} mois`) : y === 1 ? `1 an, ${m} mois` : `${y} ans, ${m} mois`,
      },
      preferences: {
        location: 'Emplacement préféré',
        locations: {
          somerled: 'Somerled',
          'cote-des-neiges': 'Côte-des-Neiges',
          either: 'Les deux nous vont',
        },
        startDate: 'Date de début souhaitée',
        startDateHint: 'Une estimation suffit — nous trouverons ensemble.',
        careType: 'Type de garde',
        careTypes: { 'full-time': 'Temps plein', 'part-time': 'Temps partiel' },
      },
      contact: {
        parentName: 'Votre nom',
        parentNamePh: 'Camille Dupont',
        email: 'Courriel',
        emailPh: 'vous@exemple.com',
        phone: 'Téléphone',
        phonePh: '(514) 000-0000',
        heardFrom: 'Comment nous avez-vous découverts ? (facultatif)',
        heardFromPh: 'Un ami, Instagram, en passant…',
        notes: 'Quelque chose à savoir ? (facultatif)',
        notesPh: 'Allergies, fratrie déjà chez nous, jours particuliers…',
      },
      validation: {
        required: 'À remplir, s’il vous plaît',
        emailInvalid: 'Ce courriel semble incorrect',
        phoneShort: 'Téléphone trop court',
        dateInPast: 'La date doit être dans le passé',
      },
    },
  },
  footer: {
    en: {
      tagline: 'A small Montessori daycare with two homes in Montréal.',
      addr: '6624 av. Somerled · 6620 Côte-des-Neiges',
      phone: '(514) 574-4695',
      email: 'info@ilecoco.com',
      hours: 'Mon — Fri · 7:30 to 18:00',
      col1: 'Visit',
      col1Items: ['Programs', 'Tuition', 'Locations', 'Gallery'],
      col2: 'Family',
      col2Items: ['Waiting List', 'FAQ', 'Contact', 'Newsletter'],
      col3: 'Stay close',
      col3Items: ['Instagram', 'Facebook', 'YouTube', 'Email us'],
      copyright: '© 2026 Ile CoCo · Made with care in Montréal',
    },
    fr: {
      tagline: 'Une petite garderie Montessori avec deux foyers à Montréal.',
      addr: '6624 av. Somerled · 6620 Côte-des-Neiges',
      phone: '(514) 574-4695',
      email: 'info@ilecoco.com',
      hours: 'Lun — Ven · 7h30 à 18h00',
      col1: 'Visiter',
      col1Items: ['Programmes', 'Frais', 'Emplacements', 'Galerie'],
      col2: 'Famille',
      col2Items: ["Liste d'attente", 'FAQ', 'Contact', 'Infolettre'],
      col3: 'Rester proche',
      col3Items: ['Instagram', 'Facebook', 'YouTube', 'Écrivez-nous'],
      copyright: '© 2026 Ile CoCo · Fait avec soin à Montréal',
    },
  },
} as const

export const PHOTOS = {
  hero1: '/images/ile-coco/apple-picking.jpg',
  hero2: '/images/ile-coco/baby-reading.jpg',
  mission: '/images/ile-coco/classroom-bright.jpg',
  why: '/images/ile-coco/educator-selfie.jpg',
  journey1: '/images/ile-coco/water-play.jpg',
  journey2: '/images/ile-coco/snow-play.jpg',
  journey3: '/images/ile-coco/apple-picking.jpg',
  gallery1: '/images/ile-coco/hallway-monkeys.jpg',
  gallery2: '/images/ile-coco/classroom-bright.jpg',
  gallery3: '/images/ile-coco/playroom-bouncy.jpg',
  gallery4: '/images/ile-coco/treehouse.jpg',
  gallery5: '/images/ile-coco/meals-art.jpg',
  gallery6: '/images/ile-coco/santa-group.jpg',
  gallery7: '/images/ile-coco/staff-costumes.jpg',
  gallery8: '/images/ile-coco/water-play.jpg',
  loc1: '/images/ile-coco/hallway-monkeys.jpg',
  loc2: '/images/ile-coco/playroom-bouncy.jpg',
  testimonial1: 'https://images.unsplash.com/photo-1542385151-efd9000785a0?w=300&auto=format&fit=crop',
  testimonial2: 'https://images.unsplash.com/photo-1588075592446-265fd1e6e76f?w=300&auto=format&fit=crop',
  testimonial3: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=300&auto=format&fit=crop',
  social1: '/images/ile-coco/meals-art.jpg',
  social2: '/images/ile-coco/staff-costumes.jpg',
  social3: '/images/ile-coco/treehouse.jpg',
  social4: '/images/ile-coco/santa-group.jpg',
  social5: '/images/ile-coco/snow-play.jpg',
  social6: '/images/ile-coco/baby-reading.jpg',
} as const
